"""sales table

Revision ID: 6305fe90f47c
Revises: 
Create Date: 2020-08-14 17:23:33.635203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6305fe90f47c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.Column('property_type', sa.String(length=1), nullable=True),
    sa.Column('new_build', sa.String(length=1), nullable=True),
    sa.Column('free_or_leasehold', sa.String(length=1), nullable=True),
    sa.Column('paon', sa.String(length=64), nullable=True),
    sa.Column('saon', sa.String(length=64), nullable=True),
    sa.Column('street', sa.String(length=64), nullable=True),
    sa.Column('locality', sa.String(length=64), nullable=True),
    sa.Column('town_city', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('county', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    # ### end Alembic commands ###
